### ISSUE TITLE
Criação de um footer

### ISSUE THREAD

**Issue by Wanhenri** [Wanhenri/duvida_flask_react#22]
Como criar um footer fixo na parte inferior?

**Comment by reisdev** [comment]
O footer pode ser posicionado ao fim da página utilizando as propriedas de css `position` e `bottom`, como o exemplo abaixo:
```css
.footer {
    position: fixed;
    bottom: 0;
}
```
A partir disso, o elemento estará fixado na parte inferior da tela. O mesmo vale para as propriedas `left`,`right` e `top`(que é usado pro header)
